# Generated by Django 3.0.2 on 2020-01-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addtasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=80)),
                ('tid', models.TextField(help_text='Enter the text')),
                ('status', models.TextField(help_text='Enter the status')),
                ('pubDate', models.DateTimeField()),
            ],
        ),
    ]
