# Generated by Django 3.0.2 on 2020-01-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addtasks',
        ),
    ]
